---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jaeger-route
  namespace: observability
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jaeger.docker.localhost`)
      kind: Rule
      services:
        - name: simplest-query
          namespace: observability
          port: 16686
