debug = true
checkNewVersion = false
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[api]

[entryPoints]
  [entryPoints.http]
  address = ":80"

[tracing]
    backend = "jaeger"
    servicename = "traefik"
    [tracing.jaeger]
    SamplingType = "const"
    LocalAgentHostPort = "jaeger:6831"
    SamplingServerURL = "http://jaeger:5778/sampling"
    SamplingParam = 1.0

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedbydefault = false
